"""
Itinerary Option Database Model

Represents pre-computed itinerary options generated by the Optimization Agent.
Travel agents review and approve/reject these options (human-in-the-loop).
"""

from datetime import datetime
from typing import Optional
from uuid import UUID, uuid4
from enum import Enum

from sqlmodel import Field, SQLModel, Column
from sqlalchemy.dialects.postgresql import JSONB


class OptionStatus(str, Enum):
    """Lifecycle status of an itinerary option"""
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ItineraryOptionDB(SQLModel, table=True):
    """
    Itinerary option model for human-in-the-loop agent workflow.

    Options are created by the Optimization Agent and presented to travel agents.
    Agents approve one option, which triggers downstream Tools Agent and
    Communication Agent pipelines.
    """
    __tablename__ = "itinerary_options"

    # Primary Key
    id: UUID = Field(default_factory=uuid4, primary_key=True)

    # References
    event_id: str = Field(max_length=255, index=True)  # Triggering event
    trip_id: str = Field(max_length=100, index=True)    # Related trip session
    agent_id: Optional[UUID] = Field(default=None, index=True)  # Assigned travel agent

    # Option Details
    summary: str = Field(max_length=500)            # Human-readable description
    cost: float = Field(default=0.0)                 # Estimated cost
    satisfaction: float = Field(default=0.0, ge=0.0, le=1.0)  # Predicted satisfaction (0-1)
    details: dict = Field(default_factory=dict, sa_column=Column(JSONB))  # Full itinerary diff, POI list, etc.

    # Status Lifecycle: PENDING -> APPROVED / REJECTED
    status: OptionStatus = Field(default=OptionStatus.PENDING, index=True)
    approved_by: Optional[UUID] = Field(default=None)
    approved_at: Optional[datetime] = Field(default=None)

    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow, index=True)

    class Config:
        json_schema_extra = {
            "example": {
                "event_id": "evt_456",
                "trip_id": "delhi_3day_fam123",
                "summary": "Split group A for 4 hrs, rejoin at Red Fort",
                "cost": 120.0,
                "satisfaction": 0.82,
                "details": {
                    "affected_pois": ["LOC_006", "LOC_013"],
                    "schedule_changes": [
                        {"day": 1, "action": "split", "duration_hrs": 4}
                    ]
                },
                "status": "PENDING"
            }
        }
